reactive_server/web/router.ex
defmodule ReactiveServer.Router do
  use ReactiveServer.Web, :router

  # This is the browser pipeline, defined as plug actions
  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # This is the JSON api pipeline
  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  scope "/", ReactiveServer do
    pipe_through [:browser, :browser_session]   # Use the default browser stack

    get "/", PageController, :index
    get "/signup", PageController, :signup
    post "/signup", PageController, :create

    get "/login", SessionController, :login_page, as: :login
    post "/login", SessionController, :login, as: :login
    get "/logout", SessionController, :logout, as: :logout

    resources "/users", UserController
    post "/users/:id", UserController, :update

  end

  # Other scopes may use custom stacks.
  # scope "/api", ReactiveServer do
  #   pipe_through :api
  # end
end

reactive_server/web/templates/page/index.html.eex
<div class="jumbotron">
    <h2>test.exs</h2>
    <%= if @current_user do %>
        <p class="lead">As a logged in user, you can browser users</p>
        <div id="messages"></div>
        <input id="chat-input" type="text"></input>
    <% else %>
        <p><a href="<%= login_path(@conn, :login_page) %>">Sign in</a>
        <p><a href="<%= page_path(@conn, :signup) %>">Register</a>
    <% end %>
</div>

reactive_server/web/templates/page/signup.html.eex
<div class="row">
    <div class="col-sm-6 col-centered">
    <h2>Sign up for an account</h2>

    <%= form_for @changeset, page_path(@conn, :create), [method: :post], fn f -> %>
      <%= if f.errors != [] do %>
        <div class="alert alert-danger">
          <p>Oops, something went wrong! Please check the errors below:</p>
          <ul>
            <%= for {attr, message} <- f.errors do %>
              <li><%= humanize(attr) %> <%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <label>Email address</label>
        <%= email_input f, :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <label>Nickname</label>
        <%= text_input f, :displayname, class: "form-control" %>
      </div>
        <div class="form-group">
        <label>First name</label>
        <%= text_input f, :firstname, class: "form-control" %>
      </div>
      <div class="form-group">
        <label>Last Name</label>
        <%= text_input f, :lastname, class: "form-control" %>
      </div>
        <div class="form-group">
        <label>Biography</label>
        <%= text_input f, :bio, class: "form-control" %>
      </div>
      <div class="form-group">
        <label>Password</label>
        <%= password_input f, :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= submit "Submit", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>